export const initialStories = [
    {
      id: 1,
      title: 'The Moon that Can\'t be Seen',
      author: 'Rara',
      category: 'Teen Fiction',
      keywords: ['school', 'fiction'],
      status: 'Draft',
      synopsis: '',
      cover: null,
      chapters: [],
    },
    {
      id: 2,
      title: 'Given',
      author: 'Sansa S.',
      category: 'Romance',
      keywords: ['music'],
      status: 'Draft',
      synopsis: '',
      cover: null,
      chapters: [],
    },
    {
      id: 3,
      title: 'Fish Swimming In The Sky',
      author: 'Kaenarita Faly',
      category: 'Fantasy',
      keywords: ['fantasy', 'romance'],
      status: 'Publish',
      synopsis: '',
      cover: null,
      chapters: [],
    },
    {
      id: 4,
      title: 'The Science of Fertility PCOS',
      author: 'Jessie Inchauspe',
      category: 'Non Fiction',
      keywords: ['science', 'PCOS'],
      status: 'Publish',
      synopsis: '',
      cover: null,
      chapters: [],
    },
    {
      id: 5,
      title: 'The Glucose Goddess Method',
      author: 'Jessie Inchauspe',
      category: 'Non Fiction',
      keywords: ['glucose', 'science'],
      status: 'Publish',
      synopsis: '',
      cover: null,
      chapters: [],
    },
  ];